### ISSUE TITLE
No provider error

### ISSUE THREAD

**Issue by saponifi3d** [smacker/karma-jasmine-expect-jsx#1]
Hey, thanks for making this! I was about to start writing one myself!

I am trying to use this in my project, but i'm getting the following error: `Error: No provider for "framework:jasmine-expect-jsx"! (Resolving: framework:jasmine-expect-jsx)`

Here is my frameworks section (super simple):

```
        frameworks: [
            'jasmine',
            'jasmine-expect-jsx'
        ],
```

I've tried a couple different requires and just requiring it directly into the frameworks section and using the object your exporting with no joy... any ideas would be _greatly_ appreciated!

**Comment by smacker** [comment]
Did you solve it? Maybe you need to add plugin in `plugins` section of your karma config. It works for me.

**Comment by saponifi3d** [comment]
Yeah it was the `plugins` I was silly and too used to CommonJS patterns of require.

Also, I'm getting some pretty funky output where it's all on one line, and the reporter seems to somehow break the junit reporter, so i can't have both of those. Making sure it's nothing on my end and i haven't tried the `spec` report yet. something tells me that would fix the output.

**Comment by smacker** [comment]
You should use "jasmine-expect-jsx" reporter only for output in console. It does nothing expect adds colors to diff. With junit reporter you shouldn't use it.

In my project I have 2 different commands for testing:
1. `"test": "karma start --reporters jasmine-expect-jsx,spec,coverage --single-run",` it makes fancy output in my terminal.
2. `"tc-test": "karma start --reporters teamcity,coverage --single-run --colors false"` it runs on CI server. I think you need something like this but with junit instead of teamcity reporter.
